version: '3'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: fastapi_container
    command: uvicorn src.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: streamlit_container
    command: streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app/frontend
    depends_on:
      - fastapi
