# Dockerfile.backend

# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN apt-get update \
    && apt-get install build-essential -y \
    && pip install --no-cache-dir -r requirements.txt

# Set an environment variable
ENV ENV="docker"

# Make port 8000 available to the world outside this container
EXPOSE 8001

# Command to run the FastAPI server
CMD ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--port", "8001"]
